---
- hosts: webservers
  become: true
  tasks:
    - name: copy war file to tomcat server
      copy:
        src: /var/lib/jenkins/workspace/DevCompile/target/addressbook.war
        dest: /opt/tomcat/webapps
